controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
images:
    path: /images/products/{filename}
    controller: App\Controller\ImageController::getImage